
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 10:33:27 ECT 2015
//----------------------------------------------------

package analexicosintacticoletras;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_FINLINEA = 3;
  public static final int error = 1;
  public static final int TK_ABRE = 4;
  public static final int TK_CADENA = 2;
  public static final int TK_CIERRA = 5;
  public static final int EOF = 0;
}

